export CODEX_COMPANION_SESSION_ID='5b9ae3bb-1909-49af-8ffe-54dfce8d88cd'
export CODEX_COMPANION_TRANSCRIPT_PATH='C:\Users\wolff\.claude\projects\C--Users-wolff-Projects-SurvivorPulse--claude-worktrees-sad-stonebraker-92977f\5b9ae3bb-1909-49af-8ffe-54dfce8d88cd.jsonl'
export CLAUDE_PLUGIN_DATA='C:/Users/wolff/.claude/plugins/data/codex-openai-codex'
export CODEX_COMPANION_SESSION_ID='5b9ae3bb-1909-49af-8ffe-54dfce8d88cd'
export CODEX_COMPANION_TRANSCRIPT_PATH='C:\Users\wolff\.claude\projects\C--Users-wolff-Projects-SurvivorPulse--claude-worktrees-sad-stonebraker-92977f\5b9ae3bb-1909-49af-8ffe-54dfce8d88cd.jsonl'
export CLAUDE_PLUGIN_DATA='C:/Users/wolff/.claude/plugins/data/codex-openai-codex'
